### ISSUE TITLE
Give users the ability to utilize an Email relay service

### ISSUE THREAD

**Issue by TheDome** [viridIT/vSMTP#996] opened 2023-02-02 15:16 UTC
**Is your feature request related to a problem? Please describe.**
While I am a fan of the vSMTP project, i lack the ability to use another email service. 
I provide my email relay using a VM hosted on Azure. This VM however is prohibited from 
sending messages to port 25 of other machines. 
Azure recommends to use a relay service like AWS SES. This service would expect SMTP messages to arrive at a different port 
and would publish these on my behalf. 

I read the documentation and implemented the action

```rhai
#{
    preq: [
        action "log full message" || {
            log("debug", "full message: " + msg::mail());
        },
        action "forward using SES" || {
            let delivery_addr = env("SMTP_RELAY_HOST");
            log("info", "forwarding mail to SES: " + delivery_addr);
            transport::forward_all(delivery_addr);
        }
    ],
}
```

however the service responds with a missing TLS certificate, which i do not plan to use for my scenario. 
I am aware, that STARTTLS is the recommended way. However for evaluation purposes I do not like to use a certificate. 

**Describe the solution you'd like**
Add an action where I can define a relay service along with a username, password, host and port, where 
I am able to send the message for delivery.

**Comment by Mathieu-Lala** [comment] 2023-02-02 15:53
The error you got is caused by the delivery system *tls only* policy, which is not configurable for now.
The authentication is also not supported for the delivery side, it should be easy to implement.

Thank you for your issue, I will address this point in a future minor release.

**Comment by TheDome** [comment] 2023-02-02 16:41
Interestingly the delivery system also does not accept a self-signed certificate. It must be a certificate issued by another CA, if I observed right.

**Comment by Mathieu-Lala** [comment] 2023-02-15 18:52
Let me know if the solution I am working on here seems to solve your issue
https://github.com/viridIT/vSMTP/pull/1018

**Comment by TheDome** [comment] 2023-02-16 14:10
This looks very promising! 
Thanks for looking into this that fast!

**Comment by erebe** [comment] 2023-02-25 20:27
Hello,

There is an issue with the patch due to url encoding.

I have set the following rules to forward email to a trusted relay
```
      rule "forward" || {
            let user = "erebe@erebe.eu";
            let pass="xxxxxx";
            let host = "mail.gandi.net";
            let port = 25;
        transport::forward_all(`smtp://${user}:${pass}@${host}:${port}?tls=opportunistic`);
        state::faccept()
      }
```

Sadly the dilevery fails with 

```
2023-02-25T20:22:51.203153Z ERROR delivery:send:forward: Email delivery failure. error=Smtp uuid=2bbb98c6-9e62-4eb9-80e2-99a16614cd61
2023-02-25T20:22:51.203203Z  WARN delivery:send: Some send operations failed, email MoveToDeferred. uuid=2bbb98c6-9e62-4eb9-80e2-99a16614cd61
```


If I take a look at the deferred queue in `/var/spool/vsmtp/deferred`, I got the following json.
```
  "delivery": {
    "{\"type\":\"forward\",\"params\":{\"host\":\"mail.gandi.net\",\"hello_name\":null,\"port\":25,\"credentials\":[\"erebe%40erebe.eu\",\"xxxxxx\"],\"tls\":\"opportunistic\"}}": [
      [
        "nemesia.lilith@gmail.com",
        {
          "held_back": {
            "errors": [
              {
                "variant": {
                  "smtp": {
                    "error": "permanent error (535): 5.7.8 Error: authentication failed: "
                  }
                },
                "timestamp": "+002023-02-25T20:22:51.203171882Z"
              }
            ]
          }
        }
      ]
    ]
  },
```


Notice that my user, `erebe@erebe.eu` has been url encoded into `erebe%40erebe.eu` and due to that the authentification is failing.

If I edit json by hand and replace `erebe%40erebe.eu` by `erebe@erebe.eu`, after restarting vsmtp, the email is correctly sent/forwarded.

**Comment by Mathieu-Lala** [comment] 2023-03-03 19:05
I fixed the url decoding here https://github.com/viridIT/vSMTP/pull/1052

**Comment by erebe** [comment] 2023-03-06 07:34
I confirm that, it works now :)

**Comment by Mathieu-Lala** [comment] 2023-03-08 02:12
Then, we could enhance this target definition with some TLS certificate policy, but I will leave that for later.

I will close this issue, @TheDome do not hesitate to reopen it if you have problems about that. You can also join us on discord https://discord.gg/N8JGBRBshf

**Closed** 2023-03-08 02:12 UTC
